package shared

// Constant of config
const (
	// MYSQL
	CONFIG_KEY_MYSQL_ADDRESS           = "mysql.ADDRESS"
	CONFIG_KEY_MYSQL_USERNAME          = "mysql.USERNAME"
	CONFIG_KEY_MYSQL_PASSWORD          = "mysql.PASSWORD"
	CONFIG_KEY_MYSQL_DATABASE          = "mysql.DATABASE"
	CONFIG_KEY_MYSQL_NUMBER_MAX_CONNS  = "mysql.NUMBER_MAX_CONNS"
	CONFIG_KEY_MYSQL_NUMBER_IDLE_CONNS = "mysql.NUMBER_IDLE_CONNS"

	// HTTP
	CONFIG_KEY_HTTP_ADDRESS = "http.ADDRESS"
)
